config/routes.rb
RapidFTR::Application.routes.draw do

  match '/' => 'home#index', :as => :root, :via => :get

  #######################
  # USER URLS
  #######################

  resources :users do
    collection do
      get :change_password
      get :unverified
      post :update_password
      post :register_unverified
      get :contact
    end
  end

  resources :sessions, :except => :index
  match 'login' => 'sessions#new', :as => :login, :via => [:post, :get, :put, :delete]
  match 'logout' => 'sessions#destroy', :as => :logout, :via => [:post, :get, :put, :delete]
  match '/active' => 'sessions#active', :as => :session_active, :via => [:post, :get, :put, :delete]

  resources :user_preferences
  resources :password_recovery_requests, :only => [:new, :create]
  match 'password_recovery_request/:password_recovery_request_id/hide' => 'password_recovery_requests#hide', :as => :hide_password_recovery_request, :via => :delete

  resources :devices
  match 'devices/update_blacklist' => 'devices#update_blacklist', :via => :post

  resources :roles
  match 'admin' => 'admin#index', :as => :admin, :via => [:post, :get, :put, :delete]
  match 'admin/update' => 'admin#update', :as => :admin_update, :via => [:post, :get, :put, :delete]
  match 'admin/logo' => 'admin#logo', :as => :admin_logo_update, :via => [:put]

  #######################
  # CHILD URLS
  #######################

  resources :children do
    collection do
      post :sync_unverified
      post :reindex
      get :advanced_search
    end

    resources :attachments, :only => :show
    resource :duplicate, :only => [:new, :create]
  end

  get '/search', :to => 'search#search', :as => 'search'

  match '/children-ids' => 'child_ids#all', :as => :child_ids, :via => [:post, :get, :put, :delete]
  match '/children' => 'children#index', :as => :child_filter, :via => [:post, :get, :put, :delete]
  match '/children/:child_id/select_primary_photo/:photo_id' => 'children#select_primary_photo', :as => :child_select_primary_photo, :via => :put
  match '/children/:id/photo/edit' => 'children#edit_photo', :as => :edit_photo, :via => :get
  match '/children/:id/photo' => 'children#update_photo', :as => :update_photo, :via => :put
  # Legacy routing to support old Android APK
  get '/children/:model_id/photo' => 'media#show_photo', :as => :child_legacy_photo, :defaults => {:model_type => 'child'}
  get '/children/:model_id/resized_photo/:size' => 'media#show_resized_photo', :as => :child_legacy_resized_photo, :defaults => {:model_type => 'child'}
  get '/children/:model_id/photos_index' => 'media#index', :as => :photos_index, :defaults => {:model_type => 'child'}

  #######################
  # MEDIA URLS
  #######################
  get '/:model_type/:model_id/photos' => 'media#manage_photos', :as => :manage_photos
  get '/:model_type/:model_id/photo/:photo_id' => 'media#show_photo', :as => :photo
  get '/:model_type/:model_id/photo/:photo_id/resized/:size' => 'media#show_resized_photo', :as => :resized_photo
  get '/:model_type/:model_id/thumbnail(/:photo_id)' => 'media#show_thumbnail', :as => :thumbnail
  get '/:model_type/:model_id/audio(/:id)' => 'media#download_audio', :as => :audio

  #######################
  # ENQUIRY URLS
  #######################
  resources :enquiries do
    get 'matches', :on => :collection
    resources :potential_matches, :only => [:destroy, :update]
  end

  #######################
  # API URLS
  #######################

  namespace :api do
    controller :form_sections, :defaults => {:format => :json} do
      get 'form_sections', :action => :index
    end

    controller :device, :defaults => {:format => :json} do
      get 'is_blacklisted', :action => 'blacklisted'
      get 'is_blacklisted/:imei', :action => 'blacklisted'
    end

    controller :sessions, :defaults => {:format => :json} do
      post :login
      post :register
      post :logout
    end

    # CHILDREN

    resources :children do
      collection do
        get :ids, :defaults => {:format => :json}
        post :unverified, :defaults => {:format => :json}
      end

      member do
        controller :child_media do
          get 'photo(/:photo_id)', :action => 'show_photo'
          get 'audio(/:audio_id)', :action => 'download_audio'
        end
      end
    end

    # ENQUIRIES

    resources :enquiries, :defaults => {:format => :json}

    # POTENTIAL MATCH

    resources :potential_matches, :only => [:index, :show]

  end

  # Backwards compatibility with 1.2
  match '/published_form_sections', :to => 'api/form_sections#children', :via => [:post, :get, :put, :delete]

  #######################
  # FORM SECTION URLS
  #######################

  resources :standard_forms, :only => :index
  match '/standard_forms', :to => 'forms#bulk_update', :via => [:put, :post]
  resources :forms do
    resources :form_sections, :path => 'form_section', :controller => 'form_section', :only => [:index, :new, :create]
  end

  resources :form_sections, :path => 'form_section', :controller => 'form_section', :except => [:index, :new, :create] do

    collection do
      match 'save_order', :via => [:post, :get, :put, :delete]
      match 'toggle', :via => [:post, :get, :put, :delete]
    end

    resources :fields, :controller => 'fields' do
      collection do
        post 'save_order'
        post 'delete'
        post 'toggle_fields'
        post 'change_form'
      end
    end
  end

  resources :highlight_fields do
    collection do
      post :remove
    end
  end

  post :update_title_field, :to => 'highlight_fields#update_title_field'

  #######################
  # ADVANCED SEARCH URLS
  #######################

  match 'advanced_search/index', :to => 'advanced_search#index', :via => [:post, :get, :put, :delete]
  match 'advanced_search/export_data' => 'advanced_search#export_data', :as => :export_data_children, :via => :post

  #######################
  # LOGGING URLS
  #######################

  resources :system_logs, :only => :index
  match '/children/:id/history' => 'child_histories#index', :as => :child_history, :via => :get
  match '/enquiries/:id/history' => 'enquiry_histories#index', :as => :enquiry_history, :via => :get
  match '/users/:id/history' => 'user_histories#index', :as => :user_history, :via => :get

  #######################
  # REPLICATION URLS
  #######################

  resources :replications, :path => '/devices/replications' do
    collection do
      post :configuration
    end

    member do
      post :start
      post :stop
    end
  end

  resources :system_users, :path => '/admin/system_users'

  resources :system_variables, :path => '/admin/system_variables', :controller => 'system_variables', :except => [:update]
  match '/admin/system_variables' => 'system_variables#update', :via => [:put, :patch]

  #######################
  # REPORTING URLS
  #######################
  resources :reports, :only => [:index, :show]

  #######################
  # TESTING URLS
  #######################
  if Rails.env.android? || Rails.env.test? || Rails.env.development? || Rails.env.cucumber?
    match 'database/delete_data/:data_type' => 'database#delete_data', :as => :reset_data, :via => :delete
    match 'database/reset_fieldworker' => 'database#reset_fieldworker', :as => :reset_fieldworker, :via => :delete
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @page_name = t('home.label')
    @user = User.find_by_user_name(current_user_name)
    @notifications = PasswordRecoveryRequest.to_display
    @suspect_record_count = Child.flagged.count
  end
end

app/views/home/_notifications.html.erb
<% if can? :update, User %>
  <% unless @notifications.empty? %>
    <p>These users requested password reset. Please contact them immediately.</p>
    <ul>
      <% @notifications.each do |notification| %>
        <% notification_for_user = User.find_by_user_name notification.user_name %>
        <li>
          <% if notification_for_user.nil? %>
            <%= "#{notification.user_name} at #{notification.created_at.strftime('%Y/%m/%d')}. This username does not currently exist in the system. #{link_to("[hide]", hide_password_recovery_request_path(notification), :method => :delete) }".html_safe %>
          <% else %>
            <%= "#{link_to notification.user_name, user_path(notification_for_user)} at #{notification.created_at.strftime('%Y/%m/%d')}. #{link_to("hide", hide_password_recovery_request_path(notification), :method => :delete)}".html_safe %>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/home/index.html.erb
<h2>
  <% if Enquiry.enquiries_enabled? %>
    <%= t "home.welcome" %>
  <% elsif !Enquiry.enquiries_enabled? %>
    <%= t "home.rapidreg.welcome" %>
  <% end %>
</h2>

<%= render 'notifications' %>

<p>
  <%= form_for @user, :url => user_preference_path(current_user_name), :html => {:method => :put} do |f| %>
      <%= label_tag "user_time_zone", t("home.current_time_zone") %>
      <%= f.time_zone_select "time_zone" %>
      <%= label_tag "user_locale", t("home.language") %>
      <%= f.select "locale", RapidFTR::Application::LOCALES_WITH_DESCRIPTION %>
    <p class='submitButton'>
      <%= f.submit t("buttons.save") %>
    </p>
<% end %>
</p>
<% if can? :create, Child %>
    <%= link_to t("children.register_new_child"), new_child_path %> <br/><br/>
<% end %>

<% if can? :read, Child %>
    <%= link_to t('home.view_records'), children_path %> <br/><br/>
    <%= link_to @suspect_record_count.to_s + " " + t("home.records_need_attention"), child_filter_path(:filter => "flag") %>
<% end %>

<p>
  <br/>
  <% if can?(:create, Enquiry) && enquiries_enabled %>
      <%= link_to t("enquiry.register_new_enquiry"), new_enquiry_path %> <br/><br/>
  <% end %>

  <% if can?(:view, Enquiry) && enquiries_enabled %>
      <%= link_to "#{number_of_enquiries_with_matches} #{t('enquiry.enquiries_with_potential_matches')}", matches_enquiries_path %>
  <% end %>
</p>

<br/>
<br/>